In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [29]:
df = pd.read_csv(r'/home/logistic/Downloads/Network.csv')

In [30]:
df

Screen Brightness  Processor Speed (GHz)  Memory Usage (GB)  \
0                 50                    2.3                  3   
1                 70                    1.8                  2   
2                 80                    2.5                  4   
3                 60                    2.0                  3   
4                 90                    2.8                  5   

   Network Connectivity  Battery Life (hours)  
0                     4                     6  
1                     3                     4  
2                     4                     7  
3                     4                     5  
4                     5                     8

In [31]:
x = df[['Screen Brightness','Processor Speed (GHz)','Memory Usage (GB)','Network Connectivity']].values

In [35]:
y = df[['Battery Life (hours)']].values

In [36]:
x

array([[50. ,  2.3,  3. ,  4. ],
       [70. ,  1.8,  2. ,  3. ],
       [80. ,  2.5,  4. ,  4. ],
       [60. ,  2. ,  3. ,  4. ],
       [90. ,  2.8,  5. ,  5. ]])

In [37]:
y

array([[6],
       [4],
       [7],
       [5],
       [8]])

In [38]:
from sklearn.linear_model import LinearRegression

In [40]:
reg = LinearRegression()

In [41]:
reg.fit(df[['Screen Brightness','Processor Speed (GHz)','Memory Usage (GB)','Network Connectivity']], df['Battery Life (hours)'])

LinearRegression()

In [45]:
reg.predict([[50,2.3,3.,4.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.])

In [46]:
reg.predict([[70,2.3,3.,3.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.28571429])

In [47]:
reg.predict([[90,2.3,3.,3.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.])

In [48]:
reg.predict([[90,2.3,3.,4.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.42857143])

In [49]:
reg.predict([[90,2,3.,4.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.57142857])

In [50]:
reg.predict([[90,1,1,4.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.4408921e-15])

In [51]:
reg.predict([[90,1,1,2.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1.14285714])

In [52]:
reg.predict([[90,1,1,4.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.4408921e-15])

In [53]:
  reg.predict([[90,1,1,3.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.57142857])

In [54]:
reg.predict([[70,2.3,3.,3.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.28571429])

In [55]:
 reg.predict([[100,2.3,3.,3.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.85714286])

In [56]:
 reg.predict([[30,2.3,3.,3.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.85714286])

In [57]:
 reg.predict([[10,2.3,3.,3.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7.14285714])

In [58]:
 reg.predict([[80,2.3,3.,3.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.14285714])

In [59]:
 reg.predict([[100,2.3,4.,3.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.71428571])

In [60]:
 reg.predict([[100,2.3,3.,4.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.28571429])

In [61]:
reg.predict([[80,2.3,4,3.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7.])

In [63]:
reg.predict([[80,2.5,4.,4.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7.])

In [64]:
reg.predict([[90,2.8,5.,5.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8.])

In [65]:
reg.predict([[90,3.,5.,5.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8.57142857])

In [66]:
reg.predict([[60,3.,5.,5.]])

/home/logistic/anaconda3/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.])